### ISSUE TITLE
[SPRINT 1] Crear componente para Call to Action

### ISSUE THREAD

**Issue by cinthyadirisio** [cinthyadirisio/mytinerary-pulpfiction#10]
Crear componente para Call to Action
- Invitar al usuario (icono/frase) a clickear desde el Hero/Welcome para acceder a la página de Cities
- Complementar con imágenes, animaciones, darle atractivo

**Comment by daniellfreelancer** [comment]
change:
<button> tag to <a> tag

**Comment by cinthyadirisio** [comment]
Como desarrollador quiero:
-Incentivar de forma visual al usuario final a que entre a la página principal
Para: que ingrese al sitio e interactue con él
