### ISSUE TITLE
[SPRINT 1] Modificar componente para Carrousel

### ISSUE THREAD

**Issue by cinthyadirisio** [cinthyadirisio/mytinerary-pulpfiction#15]
Modificar componente para Carrousel
- Las slides deben cambiar de forma automática
- El usuario puede mover los slides manualmente

**Comment by daniellfreelancer** [comment]
Historia de usuario:
- Como desarrollador quiero:
* Actualizar el estilo del carousel
* Crear botones y animacion automatica para el carousel
* Comprobar el codigo
- Para:
* Mejorar la experiencia del usuario final
