### ISSUE TITLE
[SPRINT 1] Crear componente para Cities

### ISSUE THREAD

**Issue by cinthyadirisio** [cinthyadirisio/mytinerary-pulpfiction#16]
Crear componente para Cities
- Usando el layout, crear la pagina de Cities, luego se agregarán las ciudades y el filtro

**Comment by daniellfreelancer** [comment]
Historia de usuario:
- Como desarrollador quiero:
* Agregar la pagina Cities.jsx, para luego agregar las ciudades y filtros
- Para:
* Poder tener una pagina, donde ver el renderizado de las ciudades ingresadas a traves del  futuro formulario de NewCities.jsx
