### ISSUE TITLE
[SPRINT 1] Crear componente para NewCity

### ISSUE THREAD

**Issue by cinthyadirisio** [cinthyadirisio/mytinerary-pulpfiction#17]
Crear componente para NewCity
- Usando el layout, crear la pagina de NewCity, luego se agregará el formulario

**Comment by daniellfreelancer** [comment]
Historia de usuario:
- Como desarrollador quiero:
* Crear la pagina NewCity, donde incluirá un formulario
- Para:
* Que el Usuario , pueda crear sus propios destinos a través del futuro formulario
