### ISSUE TITLE
[SPRINT 1] Modificar Footer

### ISSUE THREAD

**Issue by cinthyadirisio** [cinthyadirisio/mytinerary-pulpfiction#20]
Modificar Footer
- Para incluir un botón que suba al inicio de la página
- Debería contener otro menú de navegación para facilitarle la navegacion al usuario

- - Opcional: Mostrar el año con el objeto Date
- - Opcional: Agregar un boton de scroll to top

**Comment by daniellfreelancer** [comment]
Historia de usuario:

Como desarrollador quiero:
Agregar el botón "top" , para llevar al usuario al área principal de la web. => Done
Agregar el año, con el objeto new Date() y poder obtener la fecha actual en conjunto con el texto "© All Rights Reserved". => Done
Agregar otro menú de navegación en el componente Footer.
