### ISSUE TITLE
[SPRINT 1] Crear Hero/Welcome

### ISSUE THREAD

**Issue by cinthyadirisio** [cinthyadirisio/mytinerary-pulpfiction#3]
Crear rama pertinente

Crear componente para Hero/Welcome

- Mostrar y resaltar el nombre de la app MyTinerary
- Incluir slogan
- Usar distintos elementos (background, titulo, texto, boton)

*No olvidar Importar / Exportar componentes*

- Luego de pushear la rama de trabajo: armar la pull request, validar y mergear a la rama sprint-1
- Luego de mergear a sprint-1, actualizar sprint-1 en el visuaL
- Desde ahí, crear la rama de trabajo de la tarea siguiente

**Comment by daniellfreelancer** [comment]
fix cdn bootstrap

**Comment by daniellfreelancer** [comment]
done

**Comment by cinthyadirisio** [comment]
Como desarrollador quiero:
-Implementar un framework de CSS 
Para: tener una interfaz visual atractiva y atrayente
